### ISSUE TITLE
Return object for `make_config` with `hydra_convert="all"` is a `dict`

### ISSUE THREAD

**Issue by jgbos** [mit-ll-responsible-ai/hydra-zen#151] opened 2021-11-03 13:51 UTC
## Issue

When setting a parameter as a list in `make_config` the instantiated object remains a `omegaconf.ListConfig` object.  Yet when using `hydra_convert="all"` the config object becomes a `dict` type while the, but the parameter is now a `list` type.  

## Example

```python
from hydra_zen import make_config, instantiate

test = instantiate(make_config(val=[1, 2]))
# issue: type(test.val) == ListConfig

test_all = instantiate(make_config(val=[1,2], hydra_convert="all"))
# issue: type(test_all) == dict
# type(test_all["val"]) == list
```

**Comment by rsokl** [comment] 2021-11-03 14:07
I'm not sure I see what the issue is here.

By default, dicts and lists are in their omegaconf forms:

![image](https://user-images.githubusercontent.com/29104956/140075382-73fdb941-3fb4-4e30-a734-afc600380ff3.png)

And specifying `hydra_convert="all"` converts these containers to their respective primitives

![image](https://user-images.githubusercontent.com/29104956/140075503-b20d9a55-2085-4cd5-bf0a-d36cb8990e42.png)


What is the behavior that you expected?

**Comment by jgbos** [comment] 2021-11-03 15:10
I wasn't expecting the config object to be a dictionary after doing `hydra_convert="all"`.  I guess I don't see that as expected behavior.

**Comment by jgbos** [comment] 2021-11-03 15:13
Here is what lead to the issue:

1. My task function errors out because downstream code cannot handle `ListConfig`
2. Once I added `hydra_convert="all"` then my task function errors out because it expects to access parameters via `out.val`

**Comment by rsokl** [comment] 2021-11-05 14:01
Closing this unless there are other things that we should consider doing on the hydra-zen side of things about this.

**Closed by rsokl** 2021-11-05 14:01 UTC
Labels: hydra/omegaconf

**Comment by Jasha10** [comment] 2021-11-11 21:51
> I think that I was under the misapprehension that Hydra could toggle its conversion behavior locally.

There is some support for this, actually... but it is much easier to get a `DictConfig` inside of a `dict` than it is to get a `dict` inside of a `DictConfig`:
```python
test1 = instantiate({"val": {"x": 123, "_convert_": "none"}, "_convert_": "all"})
assert isinstance(test1, dict)
assert isinstance(test1["val"], DictConfig)
test2 = instantiate({"val": {"x": 123, "_convert_": "all"}, "_convert_": "none"})
assert isinstance(test2, DictConfig)
assert isinstance(test2["val"], DictConfig)
```
The cause of this inconsistency is that OmegaConf is very eager to convert dicts into DictConfigs: in `test2`, the inner "val" config object *is* converted to a `dict`, but it is then converted back to a `DictConfig` during instantiation of the outer config object.

**Comment by Jasha10** [comment] 2021-11-11 23:14
One may ask, "what's the point of setting `_convert_="all"` within a nested config if the top-level config has `_convert_="none"` (as in `test2`).
This can be useful if the nested config (or one of it's children) has a `_target_` field that points to some callable other than `builtins.dict` or `builtins.list`.
```python
test3 = instantiate({"val": {"_target_": "builtins.set", "_args_": [[1,2,3]], "_convert_": "all"}, "_convert_": "none"})
print(test3)  # prints {'val': {1, 2, 3}}
assert isinstance(test3, DictConfig)
assert isinstance(test3["val"], set)
```
